export const types = {
  FETCH_ALBUMS_PENDING: "FETCH_ALBUMS_PENDING",
  FETCH_ALBUMS_SUCCESS: "FETCH_ALBUMS_SUCCESS",
  FETCH_ALBUMS_ERROR: "FETCH_ALBUMS_ERROR",
  FETCH_PHOTOS_PENDING: "FETCH_PHOTOS_PENDING",
  FETCH_PHOTOS_SUCCESS: "FETCH_PHOTOS_SUCCESS",
  FETCH_PHOTOS_ERROR: "FETCH_PHOTOS_ERROR",
};
